import os
import requests
import argparse
import time
import json
from pathlib import Path

# Config
CACHE_FILE = Path.home() / ".gatekeeper_cache.json"
API_URL = "https://api.github.com/repos/github/gitignore/git/trees/main?recursive=1"
RAW_BASE = "https://raw.githubusercontent.com/github/gitignore/main/"

# Extension to Template Key Mapping
EXT_TO_LANG = {
    '.py': 'python', '.rs': 'rust', '.f90': 'fortran', '.f95': 'fortran', 
    '.f': 'fortran', '.c': 'c', '.cpp': 'c++', '.hpp': 'c++', '.go': 'go', 
    '.js': 'node', '.ts': 'node', '.java': 'java', '.rb': 'ruby', '.sh': 'shell',
    '.php': 'php', '.swift': 'swift', '.kt': 'kotlin', '.dart': 'dart'
}

def get_templates():
    """Fetches the template tree from GitHub or local cache."""
    if CACHE_FILE.exists() and (time.time() - CACHE_FILE.stat().st_mtime < 86400):
        try:
            with open(CACHE_FILE, 'r') as f:
                return json.load(f)
        except: pass

    print("--- Syncing template list from GitHub ---")
    try:
        res = requests.get(API_URL, timeout=10)
        res.raise_for_status()
        tree = res.json().get('tree', [])
        
        mapping = {}
        for item in tree:
            path = item['path']
            if path.endswith('.gitignore'):
                # Map 'fortran' -> 'Fortran.gitignore' or 'Global/Vim.gitignore'
                name_key = Path(path).stem.lower()
                mapping[name_key] = path
        
        with open(CACHE_FILE, 'w') as f:
            json.dump(mapping, f)
        return mapping
    except Exception as e:
        print(f"Sync failed ({e}). Using offline fallback.")
        return {'python': 'Python.gitignore', 'rust': 'Rust.gitignore', 'fortran': 'Fortran.gitignore'}

def fetch_content(rel_path):
    """Downloads content and recursively follows GitHub symlinks."""
    res = requests.get(RAW_BASE + rel_path)
    if res.status_code != 200:
        return None
    
    content = res.text.strip()
    
    # Identify symlinks: single line, no whitespace, ends in .gitignore
    if "\n" not in content and content.endswith(".gitignore"):
        print(f"  -> Following link: {rel_path} -> {content}")
        # Handle relative pathing for links in subdirectories
        if "/" not in content and "/" in rel_path:
            new_path = str(Path(rel_path).parent / content)
        else:
            new_path = content
        return fetch_content(new_path)
    
    return res.text

def generate(template_paths, output_path):
    """Merges templates into one file with deduplication."""
    seen_lines = set()
    with open(output_path, "w") as f:
        f.write("# Generated by Gatekeeper (Symlink-Aware)\n")
        
        for rel_path in template_paths:
            print(f"Merging: {rel_path}...")
            content = fetch_content(rel_path)
            
            if content:
                f.write(f"\n# --- Rules from {rel_path} ---\n")
                for line in content.splitlines():
                    clean = line.strip()
                    # Deduplicate rules, but keep comments/newlines
                    if not clean or clean.startswith("#") or clean not in seen_lines:
                        f.write(line + "\n")
                        if clean and not clean.startswith("#"):
                            seen_lines.add(clean)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate .gitignore from directory content.")
    parser.add_argument("dir", nargs="?", default=".", help="Target directory")
    parser.add_argument("-r", "--recursive", action="store_true", help="Recurse subdirectories")
    args = parser.parse_args()

    available = get_templates()
    path_root = Path(args.dir)
    pattern = "**/*" if args.recursive else "*"
    
    to_fetch = set()
    for p in path_root.glob(pattern):
        if p.is_file():
            ext = p.suffix.lower()
            if ext in EXT_TO_LANG:
                lang_key = EXT_TO_LANG[ext]
                if lang_key in available:
                    to_fetch.add(available[lang_key])

    if to_fetch:
        # Sort for deterministic output
        generate(sorted(list(to_fetch)), path_root / ".gitignore")
        print(f"\nSuccess! Created .gitignore at {path_root.absolute()}")
    else:
        print("No supported languages detected.")
